### ISSUE TITLE
Doesn't seem to work with latest datapuller (2.0.2)

### ISSUE THREAD

**Issue by kevinerrorz** [UnskilledFreak/Freakylay#2]
Hi! Overlay doesn't seem to interface or work at all with the latest Datapuller, version 2.0.2. Other overlays (well, at least the default one on the Datapuller page) seem to work fine.

**Comment by UnskilledFreak** [comment]
Hi!
Yes, there are a few breaking changes in DataPuller 2.0.2. I am working on that to get the overlay back and running with the latest DataPuller version.

**Comment by UnskilledFreak** [comment]
ive updated the overlay and it is now fully compatible with DataPuller 2.0.2, enjoy! :)
