### ISSUE TITLE
Give the option to hide the counter section

### ISSUE THREAD

**Issue by Jackamikaz** [UnskilledFreak/Freakylay#5]
And the song info as well (but I use this one). Currently I crop it with OBS but I think having the option(s) would be more elegant.
What do you think? If you want I can do the modifications myself and do a pull request.

**Comment by UnskilledFreak** [comment]
Hi,
I dont see a reason to hide even one of them but since you asking for it, there might be a reason ;)
So if both gets disabled, only modifiers are visible then, am I correct?

**Comment by Jackamikaz** [comment]
My reason is I don't personally find the counters relevant for my stream. Only the song info so my viewers can get the bsr if they want, plus it gives context.
At the same time I think there might be people that only want counters and don't think the song info is relevant for them.

At the end of the day, if both get disabled, only modifiers are visible yes. And since you can already decide to hide the modifiers, you would even be able to show nothing at all! Of course only a fool would install the mod and hide the three sections.
But then it becomes fully customizable and that would the be cherry on top of this already wonderful overlay.

**Comment by UnskilledFreak** [comment]
okay i will add the options :3

**Comment by UnskilledFreak** [comment]
Hi there,
i'm sorry for the long delay :/
I uploaded a new version 2.2.2 to github as well as the hosting server. You can now use the new hide options from the config panel. The overlay can be found as always via following URL:

http://u.unskilledfreak.zone/overlay/freakylay/latest/

**Comment by Jackamikaz** [comment]
Awesome :D 
I don't mind the delay, open source devs don't owe anything to anyone!
