### ISSUE TITLE
Album art stays at "Beat Saber".

### ISSUE THREAD

**Issue by ciretos** [UnskilledFreak/Freakylay#8]
Hello, the album art shows Beat Saber no matter which song I play. 
Is this intentional? This mod is new to me so I'm not familiar with it
Thanks

**Comment by UnskilledFreak** [comment]
I think you are using the Beta 3.0.0 version so what connection are you using?
The album art should change within a few seconds after you start playing a song. The only issue about the album art I know of right now is when playing a WIP song or a song which is not listed on beatsaver anymore. Then it falls back to the default Beat Saber logo.

**Comment by ciretos** [comment]
You're right, I downloaded an earlier version and the album art is displaying now.

Thanks
